spring:
  application:
    name: usercreation
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: postgres
    password: holyboy191
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true

  logging:
    level:
      org:
        flywaydb: DEBUG

jwt:
  secret: ${JWT_SECRET}
  expiration: 300000  # 5 minutes in milliseconds
  refresh-expiration: 86400000  # 1 day in milliseconds


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method